### ISSUE TITLE
Explore maps screen

### ISSUE THREAD

**Issue by salus-sage** [muralihr/heritagedocs#6]
problem 1: Moving map is difficult, when sliding on pondymap, the tab changes to other maps
solution: disabling slide for toggling tabs
problem2: markers are not showing

**Comment by salus-sage** [comment]
markers are not showing

**Comment by muralihr** [comment]
Added only one map as per suggestion of dinesh ;
User has to select the current app from the settings;
only the one that is selected will be visible;
